ciotool/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
import diagrams.views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^diagrams/', include('diagrams.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diagrams/urls.py
from django.conf.urls import url

from . import views


app_name = 'diagrams' # optional in case you have more than one app
urlpatterns = [
    # ex: /diagrams/
    url(r'^$', views.index, name='index'),
    # the 'name' value as called by the {% url %} template tag
    url(r'^login/$', views.login_user, name='login'),
    url(r'^(?P<diagram_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^creation/$', views.creation, name='creation'),
    url(r'^creation/add_layer/$', views.add_layer),
    url(r'^creation/add_textarea/$', views.add_textarea),
    url(r'^creation/creation_next/$', views.creation_next),
    url(r'^creation/save_diagram/$', views.save_diagram),
    url(r'^add_user/$', views.add_user, name='add_user'),
    url(r'^(?P<txt_id>[0-9]+)/modify/$', views.modify_txt, name='modify_txt'),
    # url(r'^creation/modify_txt/$', views.modify_txt, name='modify_txt'),
]

diagrams/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm


class Diagram(models.Model):
    diagram_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')


class Layer(models.Model):
    diagram = models.ForeignKey(Diagram, on_delete=models.CASCADE)
    layer_name = models.CharField(max_length=100)
    color = models.CharField(max_length=20)


class TextField(models.Model):
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    txt_name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    # file will be uploaded to MEDIA_ROOT/uploads
    upload = models.FileField(upload_to='uploads/')


class Arrow(models.Model):
    layer = models.ForeignKey(Layer, on_delete=models.CASCADE)
    direction_class = models.CharField(max_length=100)


class DiagramForm(ModelForm):
    class Meta:
        model = Diagram
        fields = ['diagram_name']


class LayerForm(ModelForm):
    class Meta:
        model = Layer
        fields = ['layer_name', 'color']


class TextFieldForm(ModelForm):
    class Meta:
        model = TextField
        fields = ['layer', 'txt_name', 'description', 'upload']

diagrams/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render, render_to_response, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from .models import Diagram, Layer, TextField, Arrow
from .models import TextFieldForm

def login_user(request):
    context = {'not_validate': False}
    logout(request)
    if request.POST:
        username = request.POST['email']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/diagrams/', {'user': user})
        else:
            context = {'not_validate': True}
    return render(request, 'diagrams/login.html', context)


@login_required(login_url='login/')
def index(request):
    latest_diagram_list = Diagram.objects.order_by('-pub_date')[:5]
    context = {'latest_diagram_list': latest_diagram_list}
    return render(request, 'diagrams/index.html', context)

def detail(request, diagram_id):
    diagram = get_object_or_404(Diagram, pk=diagram_id)
    layers = diagram.layer_set.all()
    last_layer = layers[len(layers)-1]
    return render(request, 'diagrams/detail.html', {'diagram': diagram, 'last_layer': last_layer})

def creation(request):
    diagram = Diagram(pub_date=timezone.now())
    diagram.save()
    return render(request, 'diagrams/creation.html')

def add_layer(request):
    # collect the last created diagram (most previous action) to attach layer
    diagram = Diagram.objects.latest('pub_date')
    # fetch data from the add-layer form and create new layer with it
    if request.method == "POST":
        name = request.POST['name']
        color = request.POST['color']

        layer = Layer.objects.create(
            diagram = diagram,
            layer_name = name,
            color = color
        )

        # create 5 arrows and 6 txtfields for the whole layer (rembember diagram structure)
        for i in range(5):
            TextField.objects.create(
                layer = layer
            )
            Arrow.objects.create(
                layer = layer
            )
        TextField.objects.create(layer = layer)
        return HttpResponse('')

def add_textarea(request):
    diagram = Diagram.objects.latest('pub_date')
    if request.method == 'POST':
        id_layer = int(request.POST['layer'])
        id_textarea = int(request.POST['textarea'])
        name = request.POST['name']
        description = request.POST['description']

        layer = Layer.objects.filter(diagram=diagram)[id_layer-1]
        txt = TextField.objects.filter(layer=layer)[id_textarea-1]

        txt.txt_name = name
        txt.description = description
        txt.save()
        return HttpResponse("")

def save_diagram(request):
    diagram = Diagram.objects.latest('pub_date')
    if request.method == 'POST':
        arrows = request.POST.getlist('arrows[]')
        name = request.POST['name']
        txt_content = request.POST.getlist('txt_fields[]')
        txt_layers = request.POST.getlist('txt_layers[]')

        l = Layer.objects.filter(diagram=diagram)
        print l;
        for i in range(l.count()):
            layer_var = l[i]
            layer_var.layer_name = txt_layers[i]
            layer_var.save()

        txt = TextField.objects.filter(layer__diagram=diagram)
        print txt
        for i in range(txt.count()):
            txt_var = txt[i]
            txt_var.txt_name = txt_content[i]
            txt_var.save()

        a = Arrow.objects.filter(layer__diagram=diagram)
        for i in range(a.count()):
            arrow_var = a[i]
            arrow_var.direction_class = arrows[i]
            arrow_var.save()

        diagram.diagram_name = name
        diagram.save()
        return HttpResponse("")


def add_user(request):
    users = User.objects.all()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        rol = request.POST['rol']

        user = User.objects.create_user(username, "", password)
        group = Group.objects.get(name=rol)
        group.user_set.add(user)
        user.save()
        group.save()
    return render(request, 'diagrams/create_user.html', {'users': users })

def modify_txt(request, txt_id):
    txt = get_object_or_404(TextField, pk=txt_id)
    print(txt.layer_id)
    if request.method == 'POST':
        form = TextFieldForm(request.POST, request.FILES)
        if form.is_valid():
            p = form.save(commit=False)
            txt.txt_name = p.txt_name
            txt.description = p.description
            txt.upload = p.upload
            txt.save()
            print txt.txt_name
            return redirect('/diagrams/creation/creation_next/')
    else:
        form = TextFieldForm({'layer': txt.layer, 'txt_name': txt.txt_name, 'description': txt.description, 'upload': txt.upload})        
    return render(request, 'diagrams/modify_txt.html', {'form': form, 'txt': txt})

def creation_next(request):
    diagram = Diagram.objects.latest('pub_date')
    layers = diagram.layer_set.all()

    last_layer = layers[len(layers)-1]
    return render(request, 'diagrams/creation_next.html', {'diagram': diagram, 'last_layer': last_layer})

diagrams/templates/diagrams/create_user.html
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- Import Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--Import materialize.css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diagrams/style.css' %}" />

<ul id="dropdown1" class="dropdown-content">
  <li><a href="add_user/">Crear Usuario</a></li>
  <li class="divider"></li>
  <li><a href="/diagrams/login">Logout</a></li>
</ul>
<nav>
  <div class="container nav-wrapper">
    <a href="/diagrams/" class="brand-logo" style="font-weight: 300">CIOTool</a>
    <ul class="right hide-on-med-and-down">
      <li><i class="material-icons">perm_identity</i></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ user }}<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

<main class="container" style="padding-top: 20px">
  <div class="row">
    <form class="col s6" method="post">{% csrf_token %}
      <h5 class="green-text">Introduce los datos del usuario:</h5>
      <div class="row">
        <div class="input-field col s12">
          <input id="email" name="username" type="text" class="validate">
          <label for="email">Username</label>
        </div>
        <div class="input-field col s12">
          <input id="password" name="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <h5 class="green-text">Asgina un Rol:</h5>
      <p>
        <input class="with-gap" type="radio" name="rol" id="test1" value="Usuario"/>
        <label for="test1">Usuario</label>
      </p>
      <p>
        <input class="with-gap" type="radio" name="rol" id="test2" value="Constructor"/>
        <label for="test2">Constructor</label>
      </p>
      <div style='float: right;'>
        <button class="btn waves-effect waves-light" type="submit">Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
    </form>

    <div class="col s4 offset-s2">
      <ul class="collection with-header">
        <li class="collection-header"><h5 class="green-text">Usuarios</h5></li>
        {% for user in users %}
        <li class="collection-item avatar">
          <i class="material-icons circle">perm_identity</i>
          <span class="title">{{ user }}</span>
          <p>{{ user.groups.all.0.name }}</p>
          <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</main>


<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>

diagrams/templates/diagrams/creation_next.html
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- Import Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--Import materialize.css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diagrams/style.css' %}" />



 <ul id="dropdown1" class="dropdown-content">
   {% if user.groups.all.0.name == 'Admin' %}
   <li><a href="add_user/">Crear Usuario</a></li>
   {% endif %}
   <li class="divider"></li>
   <li><a href="/diagrams/login">Logout</a></li>
 </ul>
 <nav>
   <div class="container nav-wrapper">
     <a href="/diagrams/" class="brand-logo" style="font-weight: 300">CIOTool</a>
     <ul class="right hide-on-med-and-down">
       <li><i class="material-icons">perm_identity</i></li>
       <!-- Dropdown Trigger -->
       <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ user }}<i class="material-icons right">arrow_drop_down</i></a></li>
     </ul>
   </div>
 </nav>


 <main>
   <div class="container" style="margin-top: 20px">
     <div class="row">
       <!-- Panel to VIEW the construction -->
       <div class="col s11">
         <div class="green-text" style="font-size: 20px; font-weight: 300"><b>2. </b>Adjunta documentos y modifica campos</div>
         <div class="panel">
           <div class="row" style="margin-bottom: 0">
              <div class="input-field col s6" style="margin-top: 0">
                <input style="font-style: italic" placeholder="- Introduce nombre del diagrama -"
                  id="diagram-name" type="text" class="validate" value="{{ diagram.diagram_name }}">
              </div>
            </div>
            {% for layer in diagram.layer_set.all %}
             <div class="row">
               <div class="col s3" style="text-align: center;"><textarea class='layer-name' id="txtlayer1">{{ layer.layer_name }}</textarea></div>
               {% with arr_txt=layer.textfield_set.all arr_ar=layer.arrow_set.all %}
               <div class="col s9 panel-uso detail-show">
                 <div style="background-color: {{ layer.color }};"class="capa">
                   <table>
                     <tbody>
                       <tr>
                         <td><textarea class='txt_content' href="{% url 'diagrams:modify_txt' arr_txt.0.id  %}"
                           onclick="show_description('{{ arr_txt.0.txt_name }}', '{{ arr_txt.0.description }}')"
                              id="{{ arr_txt.0.id }}">{{ arr_txt.0.txt_name }}</textarea></td>
                         <td><i id="{{ arr_ar.0.id }}" class="{{ arr_ar.0.direction_class }}" aria-hidden="true"></i></td>
                         <td><textarea class='txt_content' href="{% url 'diagrams:modify_txt' arr_txt.1.id  %}"
                           onclick="show_description('{{ arr_txt.1.txt_name }}', '{{ arr_txt.1.description }}')"
                            id="{{ arr_txt.1.id }}">{{ arr_txt.1.txt_name }}</textarea></td>
                         <td><i id="{{ arr_ar.1.id }}" class="{{ arr_ar.1.direction_class }}" aria-hidden="true"></i></td>
                         <td><textarea class='txt_content' href="{% url 'diagrams:modify_txt' arr_txt.2.id  %}"
                           onclick="show_description('{{ arr_txt.2.txt_name }}', '{{ arr_txt.2.description }}')"
                             id="{{ arr_txt.2.id }}">{{ arr_txt.2.txt_name }}</textarea></td>
                       </tr>
                     </tbody>
                   </table>
                 </div>
                 <div class="flechas" style="color: {{ layer.color }};">
                   <div class="row">
                     <table>
                       <tbody>
                         <tr>
                           <td>
                             <textarea class='txt_content' href="{% url 'diagrams:modify_txt' arr_txt.3.id  %}"
                                onclick="show_description('{{ arr_txt.3.txt_name }}', '{{ arr_txt.3.description }}')"
                                 id="{{ arr_txt.3.id }}">{{ arr_txt.3.txt_name }}</textarea>
                             <i id="{{ arr_ar.2.id }}" style="color: {{ layer.color }}" class="{{ arr_ar.2.direction_class }}" aria-hidden="true"></i>
                           </td>
                           <td>
                             <textarea class='txt_content' href="{% url 'diagrams:modify_txt' arr_txt.4.id  %}"
                                onclick="show_description('{{ arr_txt.4.txt_name }}', '{{ arr_txt.4.description }}')"
                                 id="{{ arr_txt.4.id }}">{{ arr_txt.4.txt_name }}</textarea>
                             <i id="{{ arr_ar.3.id }}" style="color: {{ layer.color }}" class="{{ arr_ar.3.direction_class }}" aria-hidden="true"></i>
                             </td>
                           <td>
                             <textarea class='txt_content' href="{% url 'diagrams:modify_txt' arr_txt.5.id  %}"
                                onclick="show_description('{{ arr_txt.5.txt_name }}', '{{ arr_txt.5.description }}')"
                                 id="{{ arr_txt.5.id }}">{{ arr_txt.5.txt_name }}</textarea>
                             <i id="{{ arr_ar.4.id }}" style="color: {{ layer.color }}" class="{{ arr_ar.4.direction_class }}" aria-hidden="true"></i>
                           </td>
                         </tr>
                       </tbody>
                     </table>
                   </div>
                 </div>
               </div>
               {% endwith %}
             </div>
              {% endfor %}
             <form id="save-diagram">{% csrf_token %}
               <button class="btn-floating btn-large waves-effect waves-light green" type="submit" name="action">
                 <i class="fa fa-floppy-o" aria-hidden="true"></i>
               </button>
             </form>
            </div>
          </div>
       </div>
     </div>
   </div>
 </main>


 <!--Import jQuery before materialize.js-->
 <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
 <script type="text/javascript" src="{% static 'diagrams/functions.js' %}"></script>

diagrams/templates/diagrams/detail.html
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- Import Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--Import materialize.css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diagrams/style.css' %}" />

<ul id="dropdown1" class="dropdown-content">
  {% if user.groups.all.0.name == 'Admin' %}
  <li><a href="add_user/">Crear Usuario</a></li>
  {% endif %}
  <li class="divider"></li>
  <li><a href="/diagrams/login">Logout</a></li>
</ul>
<nav>
  <div class="container nav-wrapper">
    <a href="#!" class="brand-logo" style="font-weight: 300">{{ diagram.diagram_name }}</a>
    <ul class="right hide-on-med-and-down">
      <li><i class="material-icons">perm_identity</i></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ user }}<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

 <main>
   <div class="container" style="margin-top: 20px">
     <div class="row">
       <!-- Panel to VIEW the construction -->
       <div class="col s9">
         <div class="panel">
           {% for layer in diagram.layer_set.all %}
            <div class="row">
              <div class="col s3" style="text-align: center;">{{ layer.layer_name }}</div>
              {% with arr_txt=layer.textfield_set.all arr_ar=layer.arrow_set.all %}
              <div class="col s9 panel-uso detail-show">
                <div style="background-color: {{ layer.color }};"class="capa">
                  <table>
                    <tbody>
                      <tr>
                        <td><textarea onclick="show_description('{{ arr_txt.0.txt_name }}', '{{ arr_txt.0.description }}', '{{ arr_txt.0.upload }}')"
                          readonly="" id="{{ arr_txt.0.id }}">{{ arr_txt.0.txt_name }}</textarea></td>
                        <td><i id="{{ arr_ar.0.id }}" class="non_click {{ arr_ar.0.direction_class }}" aria-hidden="true"></i></td>
                        <td><textarea onclick="show_description('{{ arr_txt.1.txt_name }}', '{{ arr_txt.1.description }}')"
                          readonly="" id="{{ arr_txt.1.id }}">{{ arr_txt.1.txt_name }}</textarea></td>
                        <td><i id="{{ arr_ar.1.id }}" class="non_click {{ arr_ar.1.direction_class }}" aria-hidden="true"></i></td>
                        <td><textarea onclick="show_description('{{ arr_txt.2.txt_name }}', '{{ arr_txt.2.description }}')"
                          readonly="" id="{{ arr_txt.2.id }}">{{ arr_txt.2.txt_name }}</textarea></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                {% if layer != last_layer %}
                <div class="flechas" style="color: {{ layer.color }};">
                  <div class="row">
                    <table>
                      <tbody>
                        <tr>
                          <td>
                            <textarea onclick="show_description('{{ arr_txt.3.txt_name }}', '{{ arr_txt.3.description }}')"
                              readonly="" id="{{ arr_txt.3.id }}">{{ arr_txt.3.txt_name }}</textarea>
                            <i id="{{ arr_ar.2.id }}" style="color: {{ layer.color }}" class="non_click {{ arr_ar.2.direction_class }}" aria-hidden="true"></i>
                          </td>
                          <td>
                            <textarea onclick="show_description('{{ arr_txt.4.txt_name }}', '{{ arr_txt.4.description }}')"
                              readonly="" id="{{ arr_txt.4.id }}">{{ arr_txt.4.txt_name }}</textarea>
                            <i id="{{ arr_ar.3.id }}" style="color: {{ layer.color }}" class="non_click {{ arr_ar.3.direction_class }}" aria-hidden="true"></i>
                            </td>
                          <td>
                            <textarea onclick="show_description('{{ arr_txt.5.txt_name }}', '{{ arr_txt.5.description }}')"
                              readonly="" id="{{ arr_txt.5.id }}">{{ arr_txt.5.txt_name }}</textarea>
                            <i id="{{ arr_ar.4.id }}" style="color: {{ layer.color }}" class="non_click {{ arr_ar.4.direction_class }} " aria-hidden="true"></i>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                {% endif %}
              </div>
              {% endwith %}
            </div>
            {% endfor %}
          </div>
       </div>
       <div class="col s3">
         <ul id="staggered-test" class="collection">
           <li id="txtfield-name" class="collection-item" style="font-weight: 300">
             Nombre
           </li>
           <li class="collection-item">
             <div class="input-field embed-button">
               <div class="title-input">Descripción:</div>
               <textarea id="description-box" readonly="" class="materialize-textarea thin"></textarea>
               <a class="file-url"></a>
             </div>
           </li>
           <li class="collection-item" style="font-weight: 300">
             Documento:
             <a href="" id="file-url"></a>
           </li>
         </ul>
       </div>
     </div>
   </div>
 </main>

 <!--Import jQuery before materialize.js-->
 <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
 <script type="text/javascript" src="{% static 'diagrams/functions.js' %}"></script>

diagrams/templates/diagrams/index.html
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diagrams/style.css' %}" />


<ul id="dropdown1" class="dropdown-content">
  {% if user.groups.all.0.name == 'Admin' %}
  <li><a href="add_user/">Crear Usuario</a></li>
  {% endif %}
  <li class="divider"></li>
  <li><a href="/diagrams/login">Logout</a></li>
</ul>
<nav>
  <div class="container nav-wrapper">
    <a href="/diagrams/" class="brand-logo" style="font-weight: 300">CIOTool</a>
    <ul class="right hide-on-med-and-down">
      <li><i class="material-icons">perm_identity</i></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ user }}<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>

<main>
  <div class="container" style="margin-top: 20px">
    <div class="row">
      {% if user.groups.all.0.name == 'Admin' or user.groups.all.0.name == 'Constructor'%}
      <div class="col m2">
        <p class="center-text">
          <a href="{% url 'diagrams:creation' %}" class="btn-floating btn-large waves-effect waves-light green">
            <i class="material-icons">add</i>
          </a>
        </p>
      </div>
      {% endif %}
    {% if latest_diagram_list %}
        {% for diagram in latest_diagram_list %}
        {% if diagram.diagram_name %}
          <div class="col s2">
            <div class="card">
              <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" src="http://www.myiconfinder.com/uploads/iconsets/256-256-0d4b4c3b1288008d5795655e2f96a33f-sitemap.png">
              </div>
              <div class="card-content">
                <p><b><a class='green-text' href="{% url 'diagrams:detail' diagram.id %}">{{ diagram.diagram_name}}</a></b></p>
              </div>
            </div>
          </div>
        {% endif %}
        {% endfor %}
      </div>
    {% else %}
        <p>No diagrams are available.</p>
    {% endif %}
  </div>
</main>

<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>

diagrams/templates/diagrams/modify_txt.html
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- Import Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!--Import materialize.css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diagrams/style.css' %}" />

<ul id="dropdown1" class="dropdown-content">
  <li><a href="add_user/">Crear Usuario</a></li>
  <li class="divider"></li>
  <li><a href="/diagrams/login">Logout</a></li>
s</ul>
<nav>
  <div class="container nav-wrapper">
    <a href="/diagrams/" class="brand-logo" style="font-weight: 300">CIOTool</a>
    <ul class="right hide-on-med-and-down">
      <li><i class="material-icons">perm_identity</i></li>
      <!-- Dropdown Trigger -->
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ user }}<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
  </div>
</nav>


<main class="container" style="padding-top: 20px">
  <div class="row">
    <form enctype="multipart/form-data" class="col s6" method="post">{% csrf_token %}
      <div class="row">
        <div style="margin-bottom: 10px"class="input-field col s12">
          {{ form.layer }}
        </div>
        <div class="input-field col s12">
          {{ form.txt_name }}
          <label for="{{ form.txt_name.id_for_txt_name }}">Título</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          {{ form.description }}
          <label for="{{ form.description.id_for_description }}">Descripción</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          {% if txt.upload %}
          <p>
            Fichero actual:
            <a href='{{ txt.upload.url }}'>{{txt.upload.name}}</a>
          </p>
          {% endif %}
          {{ form.upload }}
          <label for="{{ form.upload.id_for_upload }}"></label>
        </div>
      </div>
      <div style='float: right;'>
        <button class="btn waves-effect waves-light" type="submit">Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
    </form>
  </div>
</main>



<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>